name: Release notes

on:
  push:
    branches: [ master ]

jobs:
  release_notes:

    steps:
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

